### PR TITLE
Use Docker image files in dev container config

### PR DESCRIPTION
**Pull request by StevenMaude**
See opensafely-core/research-template-docker#32.

In opensafely-core/research-template-docker#57, we moved this configuration to the Docker image.

We can now update the dev container configuration here to use those Docker image files.

Note that `postAttachCommand` now becomes a string, instead of an object; the object format allows for running multiple commands in parallel:

https://containers.dev/implementors/json_reference/#formatting-string-vs-array-properties

However, for our use case, this is fine for now as we only run one simple script (that only starts R Studio currently).

### CODE REVIEW

**Comment by StevenMaude** [comment]
For this updated configuration to work, we need a new Docker image built and published following a merge of opensafely-core/research-template-docker/pull/57.

**Comment by StevenMaude** [comment]
I tested this by running the dev container tests in research-template-docker.

This edited the test workflow there to use the updated dev image built from https://github.com/opensafely-core/research-template-docker/pull/57 and a dev container JSON configuration as in this PR.

Run: https://github.com/opensafely-core/research-template-docker/actions/runs/9581024301

**Review by iaindillingham — APPROVED** [review]

**Comment by StevenMaude** [comment]
Needs a rebuild and another check following https://github.com/opensafely-core/research-template-docker/pull/59.

**Comment by StevenMaude** [comment]
I checked this in Codespaces launched from this branch:

* the end of the creation log, running the `postCreate.sh` shows `2024-06-20 10:42:04.839Z: devcontainer process exited with exit code 0`
* ehrQL syntax highlighting works
* `opensafely run run_all` works
* the R config files are edited/added as expected
* R Studio works

**Pull request merged**
