### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by CarolineMorton**
add in .idea/ folder (pycharm IDE) and all contents of analysis folder except do files and other stata files to reduce chance of leakage of data

### CODE REVIEW

**Comment by alexwalkercebm** [comment]
Looks fine, though there was a hint the other day that @sebbacon was doing something with an `/ouputs` folder?

**Comment by CarolineMorton** [comment]
Yep it is failing. I think due to this issue. I could change here or wait until ready and merge @sebbacon what do you advice?

**Comment by alexwalkercebm** [comment]
In that case we'll need to get others to make Stata outputs etc to end up in the outputs folder too. Should we add the `outputs/` folder to the `.gitignore` instead?

**Comment by sebbacon** [comment]
Ah, already done here: https://github.com/opensafely/research-template/pull/13/files

(I forgot this hasn't been merged yet)

Yes we'll have to get people to save outputs there - though I think it won't be mandatory, just a convention

**Comment by CarolineMorton** [comment]
@sebbacon could we merge this to make the gitignore more robust?

**Pull request closed without merging**
